import { ThemeProvider } from '@/components/theme-provider'
import './globals.css'
import { Inter } from 'next/font/google'
import { ToggleTheme } from '@/components/ToggleTheme'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App - Session Test',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <header className="flex flex-1 w-full border-b-2 border-slate-200 dark:border-slate-800 flex-row justify-end px-[10%] py-4">
              <ToggleTheme />
            </header>
            <h1 className="bg-clip-text text-transparent text-6xl font-bold text-center bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500 dark:bg-[radial-gradient(ellipse_at_right,_var(--tw-gradient-stops))] dark:from-sky-400 dark:to-indigo-600 pt-12">
              Welcome to Session Test!
            </h1>
            {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
